### ISSUE TITLE
`Unbound module Mltop` when building from source

### ISSUE THREAD

**Issue by haansn08** [uds-psl/smpl#5]
I'm trying to build this plugin from source as instructed in https://github.com/uds-psl/CoqTM
I'm on Ubuntu LTS with Coq version 8.11.

I'm getting following error when trying to build from a fresh clone:
```
$ git clone https://github.com/uds-psl/smpl
Cloning into 'smpl'...
$ cd smpl/
$ git checkout coq-8.11 
Branch 'coq-8.11' set up to track remote branch 'coq-8.11' from 'origin'.
Switched to a new branch 'coq-8.11'
$ make
coq_makefile -f _CoqProject -o Makefile.coq
make -f Makefile.coq all
make[1]: Entering directory '/tmp/smpl'
COQDEP VFILES
COQPP src/smpl.mlg
COQDEP src/smpl_plugin.mlpack
CAMLDEP src/smpl.ml
CAMLOPT -c -for-pack Smpl_plugin src/smpl.ml
File "src/smpl.ml", line 2, characters 8-30:
2 | let _ = Mltop.add_known_module __coq_plugin_name
            ^^^^^^^^^^^^^^^^^^^^^^
Error: Unbound module Mltop
make[2]: *** [Makefile.coq:626: src/smpl.cmx] Error 2
make[1]: *** [Makefile.coq:327: all] Error 2
make[1]: Leaving directory '/tmp/smpl'
make: *** [Makefile:8: all] Error 2
```

What could I do about this?

**Comment by haansn08** [comment]
The build seems to work fine with Coq 8.15, ocaml-findlib and ocaml-zarith installed.
